from dataclasses import dataclass, field


_START_MARKER = "# monopack-start"
_END_MARKER = "# monopack-end"


@dataclass(frozen=True)
class InlineConfig:
    extra_modules: set[str] = field(default_factory=set)
    extra_distributions: set[str] = field(default_factory=set)


def parse_inline_config(source: str) -> InlineConfig:
    block = _extract_managed_block(source)
    if block is None:
        return InlineConfig()

    extra_modules: set[str] = set()
    extra_distributions: set[str] = set()

    for raw_line in block.splitlines():
        line = raw_line.strip()
        if line.startswith("#"):
            line = line[1:].strip()
        if not line or ":" not in line:
            continue

        key, raw_values = line.split(":", 1)
        values = [value.strip() for value in raw_values.split(",") if value.strip()]

        normalized_key = key.strip().lower()
        if normalized_key == "extra_modules":
            extra_modules.update(values)
        elif normalized_key == "extra_distributions":
            extra_distributions.update(values)

    return InlineConfig(
        extra_modules=extra_modules,
        extra_distributions=extra_distributions,
    )


def rewrite_inline_config(source: str, config: InlineConfig) -> str:
    block = _canonical_block(config)
    start_end = _find_managed_block_bounds(source)
    if start_end is None:
        return f"{block}\n{source}"

    start_index, end_index = start_end
    return f"{source[:start_index]}{block}{source[end_index:]}"


def _extract_managed_block(source: str) -> str | None:
    bounds = _find_managed_block_bounds(source)
    if bounds is None:
        return None

    start_index, end_index = bounds
    managed_block = source[start_index:end_index]
    lines = managed_block.splitlines()
    if len(lines) < 2:
        return ""

    return "\n".join(lines[1:-1])


def _find_managed_block_bounds(source: str) -> tuple[int, int] | None:
    start_index = source.find(_START_MARKER)
    if start_index == -1:
        return None

    end_marker_index = source.find(_END_MARKER, start_index)
    if end_marker_index == -1:
        return None

    start_line_index = source.rfind("\n", 0, start_index)
    if start_line_index == -1:
        start_line_index = 0
    else:
        start_line_index += 1

    end_line_index = source.find("\n", end_marker_index)
    if end_line_index == -1:
        end_line_index = len(source)
    else:
        end_line_index += 1

    return start_line_index, end_line_index


def _canonical_block(config: InlineConfig) -> str:
    sorted_modules = ", ".join(sorted(config.extra_modules))
    sorted_distributions = ", ".join(
        sorted(config.extra_distributions, key=str.lower)
    )

    return (
        "# monopack-start\n"
        "# AUTOGENERATED by monopack. Manual edits may be overwritten.\n"
        f"# extra_modules: {sorted_modules}\n"
        f"# extra_distributions: {sorted_distributions}\n"
        "# monopack-end\n"
    )
